global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aica-sys'
    environment: 'production'

# アラートマネージャー設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# アラートルール
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# スクレイプ設定
scrape_configs:
  # Prometheus自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'

  # Frontend
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter (システムメトリクス)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
