apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'SLACK_WEBHOOK_URL_HERE'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
        - match:
            severity: critical
          receiver: 'critical'
          continue: true
        - match:
            severity: warning
          receiver: 'warning'

    receivers:
      - name: 'default'
        slack_configs:
          - channel: '#aica-sys-alerts'
            title: 'AICA-SyS Alert'
            text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'

      - name: 'critical'
        slack_configs:
          - channel: '#aica-sys-critical'
            title: '🚨 CRITICAL ALERT'
            text: '{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}'
        email_configs:
          - to: 'ops@aica-sys.com'
            from: 'alerts@aica-sys.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'alerts@aica-sys.com'
            auth_password: 'PASSWORD'

      - name: 'warning'
        slack_configs:
          - channel: '#aica-sys-warnings'
            title: '⚠️ Warning Alert'
            text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-data
              mountPath: /alertmanager
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
        - name: alertmanager-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      name: http
