"""Initial migration with automated content

Revision ID: 223a0ac841bb
Revises:
Create Date: 2025-10-14 15:11:28.677967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "223a0ac841bb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("source_id", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("key_points", sa.JSON(), nullable=False),
        sa.Column("sentiment", sa.String(length=50), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("read_time", sa.Integer(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_jobs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("items_collected", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "newsletters",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("subscribers", sa.Integer(), nullable=False),
        sa.Column("open_rate", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=False),
        sa.Column("current_period_end", sa.DateTime(), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "trends",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("impact", sa.String(length=50), nullable=False),
        sa.Column("related_articles", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subscription_status", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # Automated Content Tables (Manual Addition)
    op.create_table(
        "automated_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("slug", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_metadata", sa.JSON(), nullable=True),
        sa.Column("seo_data", sa.JSON(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automated_contents_content_type"),
        "automated_contents",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automated_contents_slug"), "automated_contents", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_automated_contents_created_at"),
        "automated_contents",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "trend_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trend_name", sa.String(length=200), nullable=True),
        sa.Column("trend_score", sa.Float(), nullable=True),
        sa.Column("source_count", sa.Integer(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("related_topics", sa.JSON(), nullable=True),
        sa.Column("data_snapshot", sa.JSON(), nullable=True),
        sa.Column("detected_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trend_data_trend_name"), "trend_data", ["trend_name"], unique=False
    )
    op.create_index(
        op.f("ix_trend_data_detected_at"), "trend_data", ["detected_at"], unique=False
    )

    op.create_table(
        "source_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("source_metadata", sa.JSON(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_data_source_type"), "source_data", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_source_data_collected_at"),
        "source_data",
        ["collected_at"],
        unique=False,
    )

    op.create_table(
        "content_generation_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("generation_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("api_cost", sa.Float(), nullable=True),
        sa.Column("generation_time", sa.Float(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_generation_logs_created_at"),
        "content_generation_logs",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Automated Content Tables (Manual Removal)
    op.drop_index(
        op.f("ix_content_generation_logs_created_at"),
        table_name="content_generation_logs",
    )
    op.drop_table("content_generation_logs")

    op.drop_index(op.f("ix_source_data_collected_at"), table_name="source_data")
    op.drop_index(op.f("ix_source_data_source_type"), table_name="source_data")
    op.drop_table("source_data")

    op.drop_index(op.f("ix_trend_data_detected_at"), table_name="trend_data")
    op.drop_index(op.f("ix_trend_data_trend_name"), table_name="trend_data")
    op.drop_table("trend_data")

    op.drop_index(
        op.f("ix_automated_contents_created_at"), table_name="automated_contents"
    )
    op.drop_index(op.f("ix_automated_contents_slug"), table_name="automated_contents")
    op.drop_index(
        op.f("ix_automated_contents_content_type"), table_name="automated_contents"
    )
    op.drop_table("automated_contents")

    # Original Tables
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("trends")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_table("newsletters")
    op.drop_table("collection_jobs")
    op.drop_table("articles")
    op.drop_table("analysis_results")
    # ### end Alembic commands ###
