"""Initial migration

Revision ID: 4741adeef488
Revises: 
Create Date: 2025-09-11 23:00:54.585058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4741adeef488'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_analysis_results_created_at'), table_name='analysis_results')
    op.drop_index(op.f('idx_analysis_results_sentiment'), table_name='analysis_results')
    op.drop_index(op.f('idx_analysis_results_source_id'), table_name='analysis_results')
    op.drop_index(op.f('idx_articles_author'), table_name='articles')
    op.drop_index(op.f('idx_articles_is_premium'), table_name='articles')
    op.drop_index(op.f('idx_articles_published_at'), table_name='articles')
    op.drop_index(op.f('idx_collection_jobs_created_at'), table_name='collection_jobs')
    op.drop_index(op.f('idx_collection_jobs_status'), table_name='collection_jobs')
    op.drop_index(op.f('idx_newsletters_published_at'), table_name='newsletters')
    op.drop_index(op.f('idx_newsletters_subscribers'), table_name='newsletters')
    op.drop_index(op.f('idx_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_trends_category'), table_name='trends')
    op.drop_index(op.f('idx_trends_created_at'), table_name='trends')
    op.drop_index(op.f('idx_trends_impact'), table_name='trends')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_subscription_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_trends_impact'), 'trends', ['impact'], unique=False)
    op.create_index(op.f('idx_trends_created_at'), 'trends', ['created_at'], unique=False)
    op.create_index(op.f('idx_trends_category'), 'trends', ['category'], unique=False)
    op.create_index(op.f('idx_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('idx_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('idx_newsletters_subscribers'), 'newsletters', ['subscribers'], unique=False)
    op.create_index(op.f('idx_newsletters_published_at'), 'newsletters', ['published_at'], unique=False)
    op.create_index(op.f('idx_collection_jobs_status'), 'collection_jobs', ['status'], unique=False)
    op.create_index(op.f('idx_collection_jobs_created_at'), 'collection_jobs', ['created_at'], unique=False)
    op.create_index(op.f('idx_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('idx_articles_is_premium'), 'articles', ['is_premium'], unique=False)
    op.create_index(op.f('idx_articles_author'), 'articles', ['author'], unique=False)
    op.create_index(op.f('idx_analysis_results_source_id'), 'analysis_results', ['source_id'], unique=False)
    op.create_index(op.f('idx_analysis_results_sentiment'), 'analysis_results', ['sentiment'], unique=False)
    op.create_index(op.f('idx_analysis_results_created_at'), 'analysis_results', ['created_at'], unique=False)
    # ### end Alembic commands ###
